version: '3.7'

services:
  mysql-db:
    image: mysql:8
    container_name: real-estate-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'real_estate'
      MYSQL_ROOT_PASSWORD: 'Secret123'
    ports:
      - '3306:3306'